version: "3.8"

services:
  aitagent:
    build: .
    container_name: aitagent
    ports:
      - "8080:8080"
    env_file:
      - .serverenv
    volumes:
      - ./data:/aitagent/data
    restart: unless-stopped

  ait-mcp:
    image: ait-mcp:latest
    container_name: ait-mcp
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
    restart: unless-stopped

volumes:
  ollama_data:
