from enum import Enum


class InspectionType(str, Enum):
    FULL_AND_PARTIAL_TEST = "FULL_AND_PARTIAL_TEST"
    FULL_TEST_ONLY = "FULL_TEST_ONLY"
    EXTENDED_AND_STANDARD_TEST = "EXTENDED_AND_STANDARD_TEST"
    EXTENDED_TEST = "EXTENDED_TEST"
